apiVersion: v1
kind: Pod

metadata:
  name: hls-service
  labels:
    app: hls-service

spec:    
  volumes:
  - name: live-stream
    emptyDir: {}
      

  containers:

  - name: video-source
    image: m5p3nc3r/hlsstream:latest
    volumeMounts:
    - name: live-stream
      mountPath: /live

    resources:
      requests:
        smarter-devices/video0: 1
      limits:
        smarter-devices/video0: 1

    args: ["-o", "/live", "-d", "/dev/video0"]

      
  - name: video-server
    image: m5p3nc3r/hlsserver:latest
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - name: live-stream
      mountPath: /usr/share/nginx/html/live
